version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: cache-db
    environment:
      POSTGRES_DB: ignite_demo
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U testuser" ]
      interval: 5s
      retries: 5

  ignite:
    image: apacheignite/ignite:2.16.0
    container_name: ignitetest
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "10800:10800"   # Thin client
      - "47100:47100"   # Discovery
      - "47500-47509:47500-47509"
    volumes:
      - ./ignite-config.xml:/opt/ignite/config/ignite-config.xml
      - ./postgresql-42.7.3.jar:/opt/ignite/libs/postgresql-42.7.3.jar
      - ./ignite-server-1.0.0.jar:/opt/ignite/libs/ignite-server-1.0.0.jar
    environment:
      CONFIG_URI: file:///opt/ignite/config/ignite-config.xml
      USER_LIBS: "/opt/ignite/libs/postgresql-42.7.3.jar:/opt/ignite/libs/ignite-server-1.0.0.jar"
      IGNITE_QUIET: "false"
      IGNITE_LOG_LEVEL: DEBUG
